### ISSUE TITLE
ModuleCheckTest errors

### ISSUE THREAD

**Issue by xdewnik** [InsertKoinIO/koin-samples#1]
Hello, just pulled your sample, trying to run your tests, but getting this errors in `ModuleCheckTest` . What did i do wrong?

`org.koin.core.error.InstanceCreationException: Could not create instance for 
 [type:Factory,class:'fr.ekito.myweatherapp.view.detail.DetailViewModel']

	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
	at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.kt:37)
	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:71)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:141)
	at org.koin.core.scope.Scope.get(Scope.kt:131)
	at org.koin.core.Koin.get(Koin.kt:107)
	at org.koin.test.check.CheckModulesKt.checkMainDefinitions(CheckModules.kt:60)
	at org.koin.test.check.CheckModulesKt.checkModules(CheckModules.kt:38)
	at org.koin.test.check.CheckModulesKt.checkModules(CheckModules.kt:25)
	at org.koin.test.check.CheckModulesKt.checkModules$default(CheckModules.kt:25)
	at fr.ekito.myweatherapp.ModuleCheckTest.testLocalConfiguration(ModuleCheckTest.kt:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
        Caused by: org.koin.core.error.NoParameterFoundException: Can't get parameter value #0 from 
        org.koin.core.parameter.DefinitionParameters@4ef782af
	at org.koin.core.parameter.DefinitionParameters.elementAt(DefinitionParameters.kt:31)
	at org.koin.core.parameter.DefinitionParameters.component1(DefinitionParameters.kt:33)
	at fr.ekito.myweatherapp.di.App_moduleKt$weatherAppModule$1$3.invoke(app_module.kt)
	at fr.ekito.myweatherapp.di.App_moduleKt$weatherAppModule$1$3.invoke(app_module.kt)
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
	... 32 more

`

**Comment by tranminhtan** [comment]
@xdewnik were you able to launch the app? It doesn't work for me, it keeps crashing when launching. I don't have any issue with the Tests
